GET http://localhost:3000/users

###
POST http://localhost:3000/users
content-Type: application/json

{
  "name": "Alex2",
  "about": "обо мне",
  "avatar": "http/link"
}
###
GET http://localhost:3000/cards
###

POST http://localhost:3000/cards
content-Type: application/json

{
  "name": "Alex3",
  "link": "обо мне"
}